## workflow parameters
# file name extension
ext: '.fastq.gz'
# The suffix added to reads
reads: ["_R1","_R2"]
# No. of reads to downsample (leave empty for no downsampling)
downsample:
# Trim the reads?
trim: True
# Additional optional passed to trimmer (default assumes nextSeq data with Illumina smallRNA barcodes)
trimmerOptions: "-q 30 --trim-n --minimum-length 20"
# List of cell barcodes
barcode_list: '/hpc/hub_oudenaarden/group_references/cell_barcodes/maya_384NLA.bc'
# path to BWA index (basename)
bwa_index: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/BWAIndex/genome.fa'
# Path to genome fasta file
genome_fasta: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/genome_fasta/genome.fa'
# Path to GTF file
gtf_file: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/annotation/genes.gtf'
# regions to remove from signal extraction
blacklist_bed: "/hpc/hub_oudenaarden/vbhardwaj/annotations/blacklists/hg38-blacklist.v2.bed"
# genome size (for MACS2 peak calling)
genomeSize: 2913022398
# context to select to create bed files (empty means consider all contexts)
bedContext:
# bin size to count CpG methylation/ChIC-fragments (result is bins*cells matrix)
binSize:
# Does the sample contain lambda phage as methylation control
lambda_phage: True
# minimum mapq threshold to extract signal from
min_mapq:
# which protocol? (options: 'nla-taps', 'chic-taps', 'chic')
method:
# also count reads on genes/regions?
countRegions:
