## workflow parameters
reads: ["_R1","_R2"]
downsample:
trim: True
trimmerOptions: ""
barcode_list: '/path/to/taps_barcodes.tsv'
bwa_index: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/BWAIndex/genome.fa'
genome_fasta: '/hpc/hub_oudenaarden/vbhardwaj/annotations/hg38_gencode31_extra/genome_fasta/genome.fa'
blacklist_bed: "/hpc/hub_oudenaarden/vbhardwaj/annotations/blacklists/hg38-blacklist.v2.bed"
min_mapq: 10
method: 'chic'
