# scChICflow snakemake profile configuration for SLURM cluster execution
jobname: '{rule}.{wildcards}.{jobid}'
executor: slurm

keep-going: True
printshellcmds: True
latency-wait: 600 # seconds
retries: 2

# To use the conda environment, source your conda.sh and activate the environment before each job
precommand: 'source /path/to/conda.sh && conda activate chicflow'

# Default resources
default-resources:
  runtime: f"{4 * attempt}h" # hours
  cpus_per_task: 8
  mem_mb: f"{32768 * attempt}"
  disk_mb: f"{input.size_mb * (1 + attempt)}"
  tmpdir: "'/path/to/tmpdir'" # Change this to your tmpdir
  slurm_extra: "'--mail-type=FAIL --mail-user=your@email.com'" # Change this to your email

# Set resources per rule
set-resources:
  dna_bam_map:
    runtime: f"{4  * attempt}h"
    cpus_per_task: 24
    mem_mb: max(8 * input.size_mb * (1 + attempt), 32768)
    disk_mb: f"{4 * input.size_mb * (1 + attempt)}"
  split_tChIC:
    runtime: f"{8 * attempt}h"
    cpus_per_task: 16
    mem_mb: max(8 * input.size_mb * (1 + attempt), 65536)
  split_fastq_dna:
    runtime: f"{4 * attempt}h"
    cpus_per_task: 16
    mem_mb: f"{65536 * attempt}"
  split_fastq_rna:
    runtime: f"{4 * attempt}h"
    cpus_per_task: 8
    mem_mb: f"{65536 * attempt}"
  split_fastq_both:
    runtime: f"{4 * attempt}h"
    cpus_per_task: 16
    mem_mb: f"{65536 * attempt}"
  split_fastq_none:
    runtime: f"{4 * attempt}h"
    cpus_per_task: 16
    mem_mb: f"{65536 * attempt}"
  rna_mapReads:
    runtime: f"{4 * attempt}h"
    cpus_per_task: 16
    mem_mb: f"{65536 * (1 + attempt)}"
  rna_filterBAMunique:
    runtime: f"{4 * attempt}h"
    cpus_per_task: 16
    mem_mb: f"{65536 * attempt}"
  rna_dedupBAMunique:
    runtime: f"{4 * attempt}h"
    cpus_per_task: 16
    mem_mb: f"{65536 * (2 + attempt)}"
  rna_cutadapt:
    runtime: f"{4 * attempt}h"
    cpus_per_task: 16
    mem_mb: f"{65536 * attempt}"